# Generated by Django 3.1.5 on 2021-03-18 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to=events.models.get_event_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('event_type', models.CharField(choices=[('Wedding', 'Wedding'), ('Engagement', 'Engagement'), ('Baptism', 'Baptism'), ('First Communion', 'First Communion'), ('party', 'Party'), ('cultural seminars', 'Cultural seminars'), ('Funeral', 'Funeral'), ('other events', 'Other events')], default=None, max_length=30)),
                ('event_location', django_countries.fields.CountryField(default=None, max_length=2)),
                ('event_description', models.TextField()),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=None, editable=False)),
                ('video_link', models.URLField(blank=True, max_length=300, unique=True, verbose_name='Your Video Link')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventimage')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
