# Generated by Django 3.1.5 on 2021-05-04 12:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('event_location', django_countries.fields.CountryField(default=None, max_length=2)),
                ('event_description', ckeditor.fields.RichTextField(blank=True)),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=None, editable=False)),
                ('video_link', models.URLField(blank=True, max_length=255, unique=True, verbose_name='Your Video Link')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to=events.models.get_event_image_path)),
                ('event_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.eventtype')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
