# Generated by Django 3.1.5 on 2021-03-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video_link',
            field=models.URLField(blank=True, max_length=255, unique=True, verbose_name='Your Video Link'),
        ),
    ]
