# Generated by Django 3.1.5 on 2021-05-04 21:11

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_post_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_image',
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to=events.models.get_event_image_path)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_imag', to='events.event')),
            ],
        ),
    ]
