# Generated by Django 3.1.5 on 2021-05-05 10:30

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210505_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventimage',
            old_name='event_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.get_event_image_path),
        ),
    ]
