# Generated by Django 3.1.5 on 2021-05-06 21:16

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210505_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.get_event_image_path, verbose_name='Your Main Image'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.get_event_images_path),
        ),
    ]
