# Generated by Django 3.1.5 on 2021-05-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210506_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
