# Generated by Django 3.1.5 on 2021-04-26 16:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20210322_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
